-include symfonicat_analytics.dep
symfonicat_analytics.lo: /symfonicat/vendor/symfonicat/analytics/ext/symfonicat_analytics/symfonicat_analytics.c
	$(LIBTOOL) --tag=CC --mode=compile $(CC) -I. -I/symfonicat/vendor/symfonicat/analytics/ext/symfonicat_analytics $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)   -DZEND_COMPILE_DL_EXT=1 -c /symfonicat/vendor/symfonicat/analytics/ext/symfonicat_analytics/symfonicat_analytics.c -o symfonicat_analytics.lo  -MMD -MF symfonicat_analytics.dep -MT symfonicat_analytics.lo
$(phplibdir)/symfonicat_analytics.la: ./symfonicat_analytics.la
	$(LIBTOOL) --tag=CC --mode=install cp ./symfonicat_analytics.la $(phplibdir)

./symfonicat_analytics.la: $(shared_objects_symfonicat_analytics) $(SYMFONICAT_ANALYTICS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --tag=CC --mode=link $(CC) -shared $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_symfonicat_analytics) $(SYMFONICAT_ANALYTICS_SHARED_LIBADD)

