services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfonicat\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Symfonicat\Service\:
        resource: '../src/Service/'

    Symfonicat\Middleware\:
        resource: '../src/Middleware/'
